# Production values for cvibe-mcp-remote
replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/cvibe-471219/cvibe-api/cvibe-mcp-remote
  pullPolicy: Always
  tag: "latest"

# CVibe API Configuration
cvibeApi:
  url: "http://cvibe-api:80/api/v1"

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: mcp.cvibe.dev
      paths:
        - path: /mcp
          pathType: Prefix
        - path: /health
          pathType: Prefix
  tls:
    - secretName: mcp-cvibe-dev-tls
      hosts:
        - mcp.cvibe.dev

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Health checks
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

nodeSelector: {}
tolerations: []
affinity: {}
